myconfig = {
    'output_dir': '.',
    'log_dir': './logs',
    'input_dir': '.',
    'exp': 0,
    'path_size': 1000,
    'mini_batch_size': 50000,
    'mini_batches': 1500,
    'gamma': 0.995,
    'lamda': 0.97,
    'max_kl': 0.9,#0.01
    'logstd': 0.6,
    'critic_epochs': 100,
    #'critic_alpha': 0.0001,
    'critic_alpha': 0.001,
    'discriminator_epochs': 100,
    'discriminator_alpha': 0.0001,
    'fvp_damping': 0.1,
    'd-steps': 10,
    'vae_epochs': 100,
    'vae_folds': 10,
    'bcloning_epochs': 100,
    'bcloning_folds': 5,
    'env_reward_lambda': 0.01,
    'plot_dir': './plots',
    'longitude_avg':0.0,
    'longitude_std':1.0,
    'latitude_avg':0.0,
    'latitude_std':1.0,
    'timestamp_avg':0.0,
    'timestamp_std':1.0,
    'course_avg':0.0,
    'course_std':1.0,
    'speed_avg':0.0,
    'speed_std':1.0,
    'dlon_avg':0.0,
    'dlon_std':1.0,
    'dlat_avg':0.0,
    'dlat_std':1.0,
    'dspeed_avg':0.0,
    'dspeed_std':1.0,
    'dcourse_avg':0.0,
    'dcourse_std':1.0


}